version: '3'
services:
  backend:
    image: 'twitch-jd-ebs:latest'
    build: .
    ports:
      - '9970:3000'
    environment:
      - MONGODB_URI=mongodb://mongodb/jd
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    volumes:
      - ~/abouth/data:/data/db
