version: '3'
services:
  backend:
    image: 'twitch-jd-ebs:latest'
    build: .
    ports:
      - '9970:3000'
    environment:
      - APP_PROTOCOL=http
      - APP_HOSTNAME=0.0.0.0
      - APP_PORT=3000
      - MONGODB_URI=mongodb://mongodb/jd
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo:latest'
    volumes:
      - ~/JDR-EBS/data:/data/db
