version: '3'
services:
  backend:
    container_name: 'JDR-EBS'
    image: 'twitch-jd-ebs:latest'
    build: .
    ports:
      - '9970:3000'

    environment:
      ##################
      #   App Config   #
      ##################
      - APP_PROTOCOL=http
      - APP_HOSTNAME=0.0.0.0
      - APP_PORT=3000
      - APP_PUBLIC_ADDRESS=http://localhost:3000

      ###################
      #  Static Config  #
      ###################
      - STATIC_ROOT_DIR=/data/static
      # - STATIC_IMAGE_DIR=images    # Relative to the Root dir
      # - STATIC_VIDEO_DIR=videos    # Relative to the Root dir

      ##################
      #   API Config   #
      ##################
      # - API_CLIENT_ID=
      # - API_CLIENT_SECRET=

      ##################
      #   Bot Config   #
      ##################
      # - BOT_USERNAME=
      # - BOT_OAUTH_TOKEN=

      ########################
      #   Extension Config   #
      ########################
      # - EXTENSION_VERSION=         # The latest Extension verson number
      # - EXTENSION_FILE_HASH=       # The latest Extension file hash
      - EXTENSION_CLIENT_ID=nv9ue0u2753fk3n1n9ghrvd28e3r9v

      ##################
      #   JWT Config   #
      ##################
      # - JWT_SECRET=

      ####################
      #   Mongo Config   #
      ####################
      - MONGODB_URI=mongodb://mongodb/jd

      #######################
      #   SocketIO Config   #
      #######################
      - SOCKETIO_CORS_ORIGINS=true       # true=reflect, false=off, any string
      # - SOCKETIO_CORS_ALLOWED_HEADERS=   # The allowed headers seperated by comma. Default: none
      # - SOCKETIO_CORS_METHODS=           # The allowed methods comma seperated. Default: GET,HEAD,PUT,PATCH,POST,DELETE
      # - SOCKETIO_CORS_CREDENTIALS=       # Sets the Access-Control-Allow-Credentials in Response. Can be true or false. Default: true

    depends_on:
      - mongodb

    volumes:
      - ~/JDR-EBS/static-data:/data/static
      - ~/JDR-EBS/song-data:/data/songs
      - ~/JDR-EBS/log-data:/home/application/log

  mongodb:
    container_name: 'JDR-MongoDB'
    image: 'mongo:latest'
    volumes:
      - ~/JDR-EBS/db-data:/data/db
